version: '3.4'

services:
  catalogdb:
    image: mongo
  catalog3.api:
    image: ${DOCKER_REGISTRY-}catalog3api
    build:
      context: .
      dockerfile: src/Catalog.API/Catalog3.API/Dockerfile
  basketdb:
    image: redis
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: src/Basket.API/Basket.API/Dockerfile

